# Generated by Django 2.0 on 2020-12-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_questionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_yes_no_question',
            field=models.BooleanField(default=False),
        ),
    ]
