# Generated by Django 2.0 on 2021-01-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_is_yes_no_question'),
        ('voting', '0008_auto_20201224_1509'),
    ]

    operations = [
    ]
