# Generated by Django 2.0 on 2021-01-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20210105_1043'),
        ('voting', '0009_merge_20210105_1029'),
    ]

    operations = [
    ]
