# Generated by Django 2.0 on 2021-01-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_merge_20210106_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='voting_type',
            field=models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('ABSOLUTA', 'ABSOLUTA'), ('RELATIVA', 'RELATIVA')], default='IDENTITY', max_length=8),
        ),
    ]
