# Generated by Django 2.0 on 2021-01-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_voting_voting_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='link',
            new_name='slug',
        ),
    ]
