# Generated by Django 2.0 on 2021-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210104_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='phone',
            field=models.CharField(max_length=100, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='totp_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TOTP Code'),
        ),
    ]
